### ISSUE TITLE
Use react hot toast promise without success message

### ISSUE THREAD

**Issue by manojgetwealthy** [timolins/react-hot-toast#264] opened 2023-01-25 06:21 UTC
There is no way to use react hot toast with a promise that should not show any success message but only show error message or loading message.

Tried following but typescript gives error:

    ```
toast.promise(promise, {
                                    loading: 'Uploading doc..',
                                    error: 'Error uploading documents. Please try again after sometime'
                                });
```

Note: React host toast is awesome by the way.

**Comment by n33pm** [comment] 2023-03-03 13:47
#179

**Comment by rcbevans** [comment] 2023-03-10 21:22
Came to look for this, but for without error message (I want promise to be cancellable and in that case, skip an error toast)

**Comment by timolins** [comment] 2023-04-29 18:34
Duplicate of #42

**Closed by timolins** 2023-04-29 18:34 UTC
