### ISSUE TITLE
Add option to limit number of toasts per call

### ISSUE THREAD

**Issue by itbeginswithi** [timolins/react-hot-toast#280] opened 2023-04-24 12:45 UTC
Currently, react-hot-toast v2 does not provide a built-in way to limit the number of toasts that can be displayed for each call to the toast method. This can lead to a large number of toasts being displayed on the screen.

It would be helpful to add an option to limit the number of toasts that can be displayed for each call to the toast method.

**Comment by timolins** [comment] 2023-04-28 15:18
Duplicate of #31

**Closed by timolins** 2023-04-28 15:18 UTC
Labels: duplicate
