### ISSUE TITLE
Toast should remain fixed on scroll at all times.

### ISSUE THREAD

**Issue by pzapo** [timolins/react-hot-toast#126] opened 2021-10-01 13:00 UTC
On scroll down it goes up and then switches back to bottom bar of the view.
On scroll up it hides with the view and the reaper at the bottom bar.

Is there way to set up toast to be fixed at all times?

**Comment by stephanbogner** [comment] 2021-12-03 09:19
This doesn't happen to me. How did you include `<Toaster/>` in your code?

**Comment by timolins** [comment] 2022-01-04 13:43
This seems to work for me. Please provide an example so we can reproduce. I'll close this issue for now.

**Closed by timolins** 2022-01-04 13:43 UTC

**Comment by remorses** [comment] 2022-06-14 15:24
In my case this was caused by `contain: paint` css prop which basically converts `absolute` positioned elements to `relative`
