### ISSUE TITLE
A vertical scroll appears with the appearance of toast

### ISSUE THREAD

**Issue by mzp23** [timolins/react-hot-toast#213] opened 2022-08-05 11:40 UTC
With the appearance of toast appears a vertical scroll 
![image](https://user-images.githubusercontent.com/48947565/183069077-aa5f6c35-9761-41b3-a397-0cb7e7696f08.png)

In my case, this is because the parent container of the toast has the property: `inset: 16px`. I fixed it by overriding the styles like this:
```
<Toaster
        containerStyle={{
          position: "relative",
          inset: "16px 0",
        }}
   />
```
It might be a good idea to set `inset:16px 0` by default

**Comment by timolins** [comment] 2023-04-29 18:38
Can you provide a code sandbox to reproduce this? I'll close it until then.

`inset: 16px` is the default because it works for all positions (left, right).

**Closed by timolins** 2023-04-29 18:38 UTC
